"""add reader model and relation

Revision ID: 969447444d15
Revises: 367680d80946
Create Date: 2023-02-18 15:00:10.593254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969447444d15'
down_revision = '367680d80946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readers',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reader_pk', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'readers', ['reader_pk'], ['pk'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reader_pk')

    op.drop_table('readers')
    # ### end Alembic commands ###
