"""empty message

Revision ID: e152ddf5620b
Revises: 8b0362960e99
Create Date: 2023-03-10 22:34:08.275262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = 'e152ddf5620b'
down_revision = '8b0362960e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    userrolesenum = postgresql.ENUM(
        'super_admin', 'admin', 'user', name='userrolesenum'
    )
    userrolesenum.create(op.get_bind())
    op.add_column(
        'user',
        sa.Column(
            'role',
            sa.Enum(
                'super_admin',
                'admin',
                'user',
                name='userrolesenum'
            ),
            nullable=False,
            server_default='user'
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
